### ISSUE TITLE
Update Font for H1 and H2

### ISSUE THREAD

**Issue by sunsheeppoplar** [sunsheeppoplar/tav-murphy-portfolio#38]
Looking at trying out

- EB Garamond
- DM Sans
- Zilla Slab
- Playfair Display FC

**Comment by sunsheeppoplar** [comment]
```css
h1 {
    font-family: futura-pt,sans-serif;
    font-size: 3.6em;
    font-weight: 700;
    font-style: normal;
    margin-bottom: -32px;
}

h4 {
    font-family: linotype-sabon, sans-serif;
    font-style: normal;
    font-weight: 400;
    margin-bottom: 14px;
}
```
